/* LabFlow Experimental Procedure editor. Loaded before app.js. */
function renumberProcedureStages() { document.querySelectorAll("#procedureStageRows .procedure-stage-index").forEach((node, index) => { node.textContent = index + 1; }); }



function updateProcedureMeasurementHint(row) { const name = row.querySelector(".procedure-stage-name").value.trim().toLowerCase(); const hint = row.querySelector(".procedure-stage-hint"); const input = row.querySelector(".procedure-stage-name"); const isMeasurementName = ["measure", "measurement", "measurements"].includes(name); if (hint) hint.hidden = !isMeasurementStage({ name }); if (input) input.classList.toggle("measurement-stage-name", isMeasurementName); }
function addProcedureStageRow(stage) { const holder = document.getElementById("procedureStageRows"); const row = document.createElement("div"); row.className = "procedure-edit-row"; row.innerHTML = '<span class="procedure-stage-index">' + (holder.children.length + 1) + '</span><input class="procedure-stage-name" required><input class="procedure-stage-duration" type="number" min="0" step="any" value="24"><select class="procedure-stage-unit"><option value="h">h</option><option value="min">min</option></select><input class="procedure-stage-location" placeholder="Optional location"><button type="button" class="secondary-button" data-remove-stage>×</button><small class="procedure-stage-hint" hidden>Measurement time: <strong>per sample</strong></small>'; holder.appendChild(row); if (stage) { row.querySelector(".procedure-stage-name").value = stage.name || ""; const duration = Number(stage.duration) || 0; row.querySelector(".procedure-stage-duration").value = duration >= 1 || duration === 0 ? duration : Math.round(duration * 60); row.querySelector(".procedure-stage-unit").value = duration >= 1 || duration === 0 ? "h" : "min"; row.querySelector(".procedure-stage-location").value = stage ? (stage.location || "") : configuredLabLocation(); } else { row.querySelector(".procedure-stage-location").value = configuredLabLocation(); } row.querySelector(".procedure-stage-name").addEventListener("input", () => updateProcedureMeasurementHint(row)); row.querySelector("[data-remove-stage]").onclick = function () { row.remove(); renumberProcedureStages(); }; updateProcedureMeasurementHint(row); }
function procedureFormModal() { const editingName = procedureEditingName; const existing = editingName ? templates[editingName] : null; openModal('<div class="modal-header"><div><h2 id="modalTitle">' + (existing ? 'Edit Procedure' : 'New Procedure') + '</h2></div><button class="close" aria-label="Close">×</button></div><form class="form" id="procedureForm"><div class="field"><label>Procedure name</label><input id="procedureName" required></div><div class="field"><label>Stages</label><div id="procedureStageRows"></div><button type="button" class="secondary-button" id="addProcedureStage">+ Add stage</button></div><div class="form-actions"><button type="button" class="secondary-button close">Cancel</button><button class="primary-button">Save</button></div></form>'); document.getElementById("procedureName").value = editingName || ""; if (existing?.stages?.length) existing.stages.forEach(stage => addProcedureStageRow(stage)); else addProcedureStageRow(); document.getElementById("addProcedureStage").onclick = () => addProcedureStageRow(); document.getElementById("procedureForm").onsubmit = function (event) { event.preventDefault(); const name = document.getElementById("procedureName").value.trim(); const stages = Array.from(document.querySelectorAll(".procedure-edit-row")).map(row => ({ name: row.querySelector(".procedure-stage-name").value.trim(), duration: (Number(row.querySelector(".procedure-stage-duration").value) || 0) * (row.querySelector(".procedure-stage-unit").value === "min" ? 1 / 60 : 1), location: row.querySelector(".procedure-stage-location").value.trim() })); if (!stages.length || !name) return; if (editingName && editingName !== name) delete templates[editingName]; templates[name] = { name, stages }; browserWrite(BROWSER_TEMPLATES_KEY, templates); procedureEditingName = null; closeModal(); render(); toast(name + " procedure saved"); }; }
function newProcedureModal() { procedureEditingName = null; procedureFormModal(); }
function editProcedureModal(name) { if (!templates[name]) return; procedureEditingName = name; procedureFormModal(); }

document.addEventListener("dblclick", event => { const card = event.target.closest?.(".procedure-card"); if (card) editProcedureModal(card.dataset.procedure); });


